### ISSUE TITLE
【Docker】MySQLコンテナお試し（3）

### ISSUE THREAD

**Issue by kyoruni** [kyoruni/til#25]
`docker-compose down` してもデータが消えないようにしたい

**Comment by kyoruni** [comment]
```
version: '3.7'
services:
  mysql:
    image: mysql:8
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - ./etc/my.cnf:/etc/mysql/conf.d/my.cnf
      - til-db-data:/var/lib/mysql
    ports:
      - 3306:3306
```

**Comment by kyoruni** [comment]
怒られた
```
Named volume "til-db-data:/var/lib/mysql:rw" is used in service "mysql" but no declaration was found in the volumes section.
```

**Comment by kyoruni** [comment]
トップレベル（一番上）にも、 volumes の定義が必要だった
```
version: '3.7'
services:
  mysql:
    image: mysql:8
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - ./etc/my.cnf:/etc/mysql/conf.d/my.cnf
      - til-db-data:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  til-db-data: ← これ！！！！！
```
